Bugfix #2058 loqusdb feature 200901
Clinical-Genomics/scout pull request #2059
Opened 2020-09-01 11:24 UTC by mikaell

This PR fixes a bug.

**How to test**:
1. Install branch.
2. In Web-GUI go to Institute settings `http://localhost:5000/overview/cust000/settings?`
3. Delete "LoqusDB id" and save
4. Go to a Variant. This should not crash.

**Expected outcome**:
The functionality should be working. No crash.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2020-09-01 11:45 UTC, northwestwitch requested changes
Tried it:
- **Locally** - and didn't really test it according to the description because I don't have any loqusdb instance running so I couldn't remove it from the settings. Local instance works! 🆗 
- **On stage** - Looks like there is some problem in the code, check this variant for instance: https://scout-stage.scilifelab.se/cust000/15026-mip7/ac1be94991570e313ecc6146b24462e0, that produces the following error:
```
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod-stage/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/utils.py", line 23, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/variant/views.py", line 48, in variant
    data["observations"] = observations(store, loqusdb, data["case"], data["variant"])
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/blueprints/variant/controllers.py", line 267, in observations
    obs_data = loqusdb.get_variant(variant_query, loqusdb_id=institute_obj.get("loqusdb_id")) or {}
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/extensions/loqus_extension.py", line 155, in get_variant
    output = execute_command(cmd)
  File "/home/hiseq.clinical/SERVER/apps/scout-stage/git/scout-stage/scout/server/extensions/loqus_extension.py", line 33, in execute_command
    cmd_string = " ".join(cmd)  # add spacing to create a command string
TypeError: sequence item 19: expected str instance, list found
```
This error does't occur with all variants, but I don't know what triggers it.

Comments: perhaps accept the suggestion of Flake8 and do the comparison of using == instead of with "is"?

2020-09-01 12:13 UTC, mikaell commented
Good find. I didn't hit those triggering variants myself at first.

Now patched. Please try again!

2020-09-01 12:24 UTC, northwestwitch commented on scout/server/extensions/loqus_extension.py
> +p                    "-s",
?

2020-09-01 12:29 UTC, northwestwitch reviewed
There is some syntax error due to a typo

2020-09-01 12:29 UTC, northwestwitch commented on scout/server/extensions/loqus_extension.py
> +        if loqusdb_id is None or loqusdb_id is "":
```suggestion
       if loqusdb_id is None or loqusdb_id is "":
```

2020-09-01 12:29 UTC, northwestwitch commented on scout/server/extensions/loqus_extension.py
> +        if loqusdb_id is None or loqusdb_id is "":
```suggestion
        if loqusdb_id is None or loqusdb_id == "":
```

2020-09-01 12:29 UTC, northwestwitch commented on scout/server/extensions/loqus_extension.py
> +        if loqusdb_id is None or loqusdb_id is "":
```suggestion
        if loqusdb_id is None or loqusdb_id == "":
```

2020-09-01 12:29 UTC, northwestwitch commented on scout/server/extensions/loqus_extension.py
> +p                    "-s",
```suggestion
                    "-s",
```

2020-09-02 06:47 UTC, mikaell commented on scout/server/extensions/loqus_extension.py
> +p                    "-s",
> There is some syntax error due to a typo
Fixed!

2020-09-02 07:12 UTC, northwestwitch approved these changes
I'm testing it for the last time on stage then we can merge I think, don't forget the CHANGELOG

2020-09-02 07:21 UTC, northwestwitch commented
It's on stage now, looks like it's working fine!

2020-09-02 07:59 UTC, mikaell commented
> I'm testing it for the last time on stage then we can merge I think, don't forget the CHANGELOG

Changelog updated. Will merge.

2020-09-02 08:00 UTC, merged