Feature remove deprecated 201020
Clinical-Genomics/scout pull request #2164
Opened 2020-10-20 12:53 UTC by mikaell

This PR adds a functionality or fixes a bug: remove calls to deprecated `Pymongo.cursor.count()`.

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2020-10-20 12:54 UTC, mikaell commented
This PR takes care of calls to `count()` that I missed in my previous PR. 

I need help in how to test all Jinja-calls. I don't know where in Scout's flow they are invoked.

2020-10-22 06:19 UTC, northwestwitch requested changes
I have a suggestion for the jinja cursor counter. Jinja calls to the counter are done in the general report :
- Case-level comments
- SNV variant comments
- SV variant comment

If you add one or more comments to these items and they show in the general report it means that the counter works.

Same for the call from clinvar submissions. This is the effect of the actual code:

![image](https://user-images.githubusercontent.com/28093618/96832490-20c1d080-143f-11eb-94f6-a038c16646f7.png)

And this is when you rewind the cursor:

![image](https://user-images.githubusercontent.com/28093618/96832577-44851680-143f-11eb-8f0e-4d538de89616.png)

2020-10-22 06:27 UTC, northwestwitch commented on scout/server/blueprints/managed_variants/controllers.py
> -    variant_count = managed_variants_query.count()
But it's up to you. This should be tested on stage or locally after adding managed variants

2020-10-26 07:56 UTC, mikaell commented on scout/server/blueprints/managed_variants/controllers.py
> -    variant_count = managed_variants_query.count()
I'll do a `clone()` instead of `rewind()`.

2020-10-26 07:57 UTC, mikaell commented on scout/server/app.py
> +        return len(list(pymongo_cursor))
I'll do a clone() instead of rewind().

2020-10-26 09:44 UTC, northwestwitch approved these changes
Testing again after the fix, and look good! 👍 

Added a couple of comments to the case, they show in report: 🆗 

![image](https://user-images.githubusercontent.com/28093618/97156903-a7481c00-1777-11eb-89af-3c4e37716ed5.png)

Added a couple of comments to a variant, they are visible as well: 🆗 

![image](https://user-images.githubusercontent.com/28093618/97157050-dd859b80-1777-11eb-9d5c-6031d03f7318.png)

Clinvar submission looks OK as well: 🆗 

![image](https://user-images.githubusercontent.com/28093618/97157143-0148e180-1778-11eb-987d-2fedbb029ea9.png)

2020-10-26 10:08 UTC, northwestwitch commented
I think that after testing that the new managed variants counter works it's fine to merge this one

2020-10-26 10:32 UTC, merged

2020-10-26 10:35 UTC, northwestwitch commented
Did you test that the counter of managed variants works in the end?

2020-10-26 10:41 UTC, mikaell commented
> Did you test that the counter of managed variants works in the end?

Honestly, I'm not sure which counter that is 🤔

Testing other counters and seeing them work, knowing that they all use the same backend function, I deducted that it should be fine.

2020-10-26 10:43 UTC, northwestwitch commented
I've installed master on stage and managed variants looks fine: https://scout-stage.scilifelab.se/managed_variant