Configurable variant options
Clinical-Genomics/scout pull request #2574
Opened 2021-04-27 10:15 UTC by mhkc

**DRAFT PR**

This PR enables storage of variant dismiss terms in mongo instead being hard coded in constants files.

It is currently only functional for variant.html

**How to test**:
1. add a dismiss term with `scout load evaluation_terms`
2. goto http://10.0.224.64:5000/cust000/643594/4c7d5c70d955875504db72ef8e1abe77
3. dismiss the variant

**Expected outcome**:
Retain current functionality

**Review:**
- [ ] code approved by
- [ ] tests executed by

2021-04-30 12:29 UTC, mhkc commented
I dont think the codefactor issues relates to changes I have made

2021-05-01 06:16 UTC, northwestwitch commented
> I dont think the codefactor issues relates to changes I have made

No, they were there since before! I took the liberty to fix them. 😃

2021-05-03 11:00 UTC, northwestwitch commented
Hi, I haven'r really started looking at the code of this PR (it's quite a big one) and I figured it's better to understand how it is supposed to work first. I've got a few questions:

1. 

1. Custom Evaluations terms will be bulk-loaded from file and saved to database when the `scout setup demo` or `scout setup database` cli command is invoked
1.  Same for variant dismiss options right?
1.  Single variant evaluation terms can also be loaded one at the time using the cli.
1. Is there a command to bulk-load all evaluation terms when you basically have a server already with data, like we have now in production?
1. Is your PR description actual (it works only for variant.html (not cancer variants, no strs, no sv?)

A consideration: 
Evaluation terms and variant dismiss options provided in don't correspond to the terms we (Stockholm) have in production at the moment:

Our prod:
![image](https://user-images.githubusercontent.com/28093618/116868472-1f076f80-ac0f-11eb-8f3a-642716e7d516.png)

This PR:
![image](https://user-images.githubusercontent.com/28093618/116868514-32b2d600-ac0f-11eb-8396-643095a0d0f8.png)


Same for dismiss options:
Our prod:
![image](https://user-images.githubusercontent.com/28093618/116868569-4eb67780-ac0f-11eb-9762-f5a4b8229bdf.png)

This PR:
![image](https://user-images.githubusercontent.com/28093618/116868603-59710c80-ac0f-11eb-9f5d-d7ac57eeac49.png)

So I think we should sit together (possibly after having reviewed and tested this PR) and decide what is standard and should be included as default terms before proceeding. What do you say @dnil?

2021-05-03 13:22 UTC, northwestwitch commented
Testing the PR. I'm not done with the review (haven't started to look at the code yet) but I have some comments that can be addressed already.

Testing the PR locally in this case scenario:

1. Pre-existent instance of Scout with rare disease case that has dismissed (with one or more reasons) and evaluated (for instance likely benign).
1. Switch to this branch and load the terms in the database:
There exist **2 commands to load terms in the database: `scout load batch-evaluation-term` and `scout load evaluation-term`.** I find a bit confusing that they have the same explanation:

![image](https://user-images.githubusercontent.com/28093618/116876896-7ad8f500-ac1d-11eb-8a9e-73a880a0b3eb.png)

-[ ] **Suggestion: Could you be a bit more specific with the help of these command so it's clearer what is the difference?**

1. The command to use would be `scout load batch-evaluation-term`. Loading the evaluation and dismissed terms using the provided resource():
```
scout --demo load batch-evaluation-term -f scout/resources/variant_manual_rank_terms.json
scout --demo load batch-evaluation-term -f scout/resources/variant_dismissal_terms.json
```
The commands work 🆗 

Looking at the variant in question: looks fine on variantS list: 

![image](https://user-images.githubusercontent.com/28093618/116878688-fdfb4a80-ac1f-11eb-9397-940b20908c6f.png)


- [ ] But doesn't show any dismissed and manual evaluated tags on the variant page:

![image](https://user-images.githubusercontent.com/28093618/116878785-1d927300-ac20-11eb-9a88-74aaa89f0cfe.png)

- [ ] Looks like there is something wrong with how the terms are collected for variant tags

![image](https://user-images.githubusercontent.com/28093618/116879031-6cd8a380-ac20-11eb-83cd-8ed05667aec2.png)

- [ ] And dismiss options:
![image](https://user-images.githubusercontent.com/28093618/116880862-ce9a0d00-ac22-11eb-9859-8f4cafb84d7c.png)

- [ ] Please check that these lists correspond to the terms that are currently present in master branch

2021-05-03 13:54 UTC, dnil commented
> * [ ]  Please check that these lists correspond to the terms that are currently present in master branch

We will likely have to live with at least two sets here for starters, since Lund have a different set. To me it would be very ok to include json for both current master and current Lund for an alternative. This would solve the more pressing issue of allowing us to work off one codebase properly. 

Getting a user group together to evaluate all terms - or send a list around for comments to all - would be very nice. But the idea is that this ought to be mergeable without a full consensus.

2021-05-03 13:58 UTC, northwestwitch commented
> We will likely have to live with at least two sets here for starters, since Lund have a different set. To me it would be very ok to include json for both current master and current Lund for an alternative.

Yes I agree, 2 lists under resources is perfect. But I think that the default one should correspond to the one we have on master

2021-05-04 08:44 UTC, mhkc commented
> We` will likely have to live with at least two sets here for starters, since Lund have a different set. To me it would be very ok to include json for both current master and current Lund for an alternative. This would solve the more pressing issue of allowing us to work off one codebase properly.

I have only included the terms you are using. They are divided into two different list depending, one for dismissal terms and one for manual rank terms. Both are loaded by default when one setup either a demo or normal database.

2021-05-05 06:37 UTC, northwestwitch commented
Testing and starting the review of this PR now. It's a fantastic refactoring work, but it touches so many files and functionalities that I am a bit scared of where breaking changes might occur. Note  to @mhkc for next time: try to break down the tasks as much as you can: It is is much easier to test and review smaller PRs. This one for instance could have been divided in sub-tasks like this

- Move variant tags to the database and establish system to load them all together from resources yaml file
- Move dismiss tags to the database using the same system as variant tags
- Add/remove one custom term to the variants evaluations using the cli
- Add the cli command to view the evaluation terms
- Institute-specific variant evaluation terms (page)


Checklist of things to test that come to my mind:

- [ ] All previous terms loaded into database.
- [ ] Previous dismissed/ranked variants still get the same evaluation
- [ ] Evaluations / ranking shows in general report
- [ ] Evaluation of old evaluated cases should show the same evaluations in general report
- [ ] Document the procedure in docs
- [ ] Add one custom evaluation term using the cli and see that it shows and works in the portal
- [ ] Try by adding one term that has the same "rank" and see what happens (it shouldn't be possible to have duplicates)
- [ ] Check institute settings page when loading a custom eval term

2021-05-05 09:50 UTC, northwestwitch requested changes
Nice with the fixes, it's getting there! Once again, I haven't started the review of the code since I think there are some tested things that don't work as they should, yet.

I'm copying the text of a previous comment and post it as review. I've included a checklist of tests and some need a bit of attention.

It's a fantastic refactoring work, but it touches so many files and functionalities that I am a bit scared of where breaking changes might occur. Note  to @mhkc for next time: try to break down the tasks as much as you can: It is is much easier to test and review smaller PRs. This one for instance could have been divided in sub-tasks like this

- Move variant tags to the database and establish system to load them all together from resources yaml file
- Move dismiss tags to the database using the same system as variant tags
- Add/remove one custom term to the variants evaluations using the cli
- Add the cli command to view the evaluation terms
- Institute-specific variant evaluation terms


Checklist of things to test that come to my mind - pics from this branch on the left - :

- [x] All previous tag terms loaded into database when setting up a database with `scout setup demo/database`
- [ ] All variant tags and  are OK for RD variant (they are, but sorted they other way around)
![image](https://user-images.githubusercontent.com/28093618/117105560-960f4600-ad7e-11eb-891f-008071725290.png)
- [x] All dismiss terms are OK for RD variant
![image](https://user-images.githubusercontent.com/28093618/117105778-0322db80-ad7f-11eb-845c-0e33b06bf031.png)
- [ ] All variant tags are OK for cancer variant (they are, but sorted they other way around)
![image](https://user-images.githubusercontent.com/28093618/117106334-f652b780-ad7f-11eb-8c0b-9d09b52d7702.png)
- [ ] All dismiss terms are OK for cancer variant. **NOPE, check pic!**
![image](https://user-images.githubusercontent.com/28093618/117106598-724cff80-ad80-11eb-9e04-647a88bf074f.png)

- [ ] Previous dismissed/ranked RD variants still get the same evaluation. **Tags are not shown on variant's page, see pic**
![image](https://user-images.githubusercontent.com/28093618/117108795-feacf180-ad83-11eb-89f7-4e4694e3a1cc.png)

- [ ] Previous dismissed/ranked cancer variants still get the same evaluation. **No evaluation shown in this branch**
![image](https://user-images.githubusercontent.com/28093618/117109044-564b5d00-ad84-11eb-98c7-680451dd589f.png)

- [x] Correct evaluation of old evaluated cases should show the same evaluations in general report (rare)
- [ ] Correct evaluation of old evaluated cases should show the same evaluations in general report (cancer). **The page crashes when using cancer-specific dismiss tags**:
```
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 779, in template
    <li>{{dismissed_options[reason|int]['description']}}
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 46
```
- [x] Batch load evaluation terms: `scout --demo load batch-evaluation-term -f scout/resources/variant_manual_rank_terms.json`
- [x] Batch load dismiss terms: `scout --demo load batch-evaluation-term -f scout/resources/variant_dismissal_terms.json`
- [ ] Document the procedure in docs. **Documentation on the 2 commands above is missing. Document also how to add a single term**.
- [ ] Add one custom evaluation term using the cli and see that it shows and works in the portal. The cli command works fine, but the syntax is too relaxed. There is only one mandatory field (name). If you provided just name you end up with a useless term added to the database: 
![image](https://user-images.githubusercontent.com/28093618/117110459-6cf2b380-ad86-11eb-89b8-426cb7cc038f.png)

    - Suggestion: make description and term-category also mandatory. 
    - Define strict term categories that can be assigned in the constants, and check that term has a valid category when created
    - What is label and what is it used for?
    - Which field is displayed on the variant page? Mention this in the help of the CLI command perhaps so user knows at the moment of term creation?
    - Description of institute option look incomplete:
    
![image](https://user-images.githubusercontent.com/28093618/117120696-f0ff6800-ad93-11eb-8269-ab133cc2e6fa.png)

    - Improve description of the `scout load batch-evaluation-term,` because it's identical to the `scout load evaluation-term` one
     
![image](https://user-images.githubusercontent.com/28093618/117118528-26ef1d00-ad91-11eb-87c7-f9946ded6b51.png)

- [x] Try by adding one term that has the same "rank" and see what happens (it shouldn't be possible to have duplicates)
- [ ] Check institute settings page when loading a custom eval term. **The field looks a but weird on institute settings page:**

![image](https://user-images.githubusercontent.com/28093618/117123535-73d5f200-ad97-11eb-9f52-8969cec31a69.png)

- [x] Check a variant with custom institute terms (should show the term)

2021-05-11 05:56 UTC, northwestwitch commented
Do you need help with this one @mhkc ? I could find time today and tomorrow to help fixing stuff

2021-05-17 14:04 UTC, northwestwitch commented on scout/server/blueprints/variant/templates/variant/buttons.html
> +            <option {% if data.rank == variant.manual_rank %} selected {% endif %} value="{{ data.rank }}">
The unrecognized old rankings and dismissed terms was due to this. The variant updated with new manual rank and dismissed terms looks like this on master:

![image](https://user-images.githubusercontent.com/28093618/118501913-7d614180-b729-11eb-8cb5-19198723e5ab.png)

2021-05-18 11:20 UTC, mhkc commented
>  All variant tags and are OK for RD variant (they are, but sorted they other way around)

I think this is acceptable. Currently `manual rank` and `dismissal term` have the same sort order (ascending rank) having different sort orders would be confusing. If we were to change the rank value of the manual rank terms then we would break backward compatibility without prior migration of the database.

2021-05-20 15:08 UTC, northwestwitch requested changes
Nicely done! I think we are getting closer now!

I have a few comments on the code.

Also: the order in which the terms are displayed is not important so it's fine to have it reverted. But I have a concern regarding the format used to save rank and dismiss info in the variant document.

On master (and on millions of variants in our prod database with have the following format:

![image](https://user-images.githubusercontent.com/28093618/118989309-38841780-b982-11eb-84e8-a6dcdaf2bb3b.png)


This branch is changing the format into:

![image](https://user-images.githubusercontent.com/28093618/118988642-aa0f9600-b981-11eb-8942-7e01d4088e4f.png)

I actually like your way because it's intuitive but think we should avoid introducing such radical changes (if possible). We will end up with a mixture of strings and numbers and it will be much more complicated to maintain. Is there a reason why you want to change the format?

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variant/controllers.py
> +    dismiss_options = build_variant_evaluation_terms(evalutation_terms)
```suggestion
    dismiss_options = build_variant_evaluation_terms(evaluation_terms)
```

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variant/controllers.py
> +    evalutation_terms = store.evaluation_terms(
```suggestion
    evaluation_terms = store.evaluation_terms(
```

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variants/views.py
> +    evalutation_terms = store.evaluation_terms(
```suggestion
    evaluation_terms = store.evaluation_terms(
```

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variants/views.py
> +    dismiss_variant_options = build_variant_evaluation_terms(evalutation_terms)
```suggestion
    dismiss_variant_options = build_variant_evaluation_terms(evaluation_terms)
```

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variants/views.py
> +    evalutation_terms = store.evaluation_terms(
```suggestion
    evaluation_terms = store.evaluation_terms(
```

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variants/views.py
> +    dismiss_variant_options = build_variant_evaluation_terms(evalutation_terms)
```suggestion
    dismiss_variant_options = build_variant_evaluation_terms(evaluation_terms)
```

2021-05-20 15:08 UTC, northwestwitch commented on scout/server/blueprints/variants/views.py
> +    manual_rank_options = build_variant_evaluation_terms(evalutation_terms)
```suggestion
    manual_rank_options = build_variant_evaluation_terms(evaluation_terms)
```

2021-05-20 15:08 UTC, northwestwitch commented on tests/adapter/mongo/test_evaluation_terms.py
> +    ##THEN assert that the generic transcript is there
Transcript?

2021-05-24 11:17 UTC, northwestwitch commented
@mhkc I've merged the conflicts but there is a test that is not passing. Could be due to the change that you mentioned (return error when the app loads if there are no evaluation terms in database). I can take a look at this later if you want!

2021-05-26 11:08 UTC, mhkc commented
@northwestwitch please do. I have been swamped with issues with the scout update

2021-05-26 13:34 UTC, northwestwitch commented
What about about splitting this one in smaller PRs instead? I'm having a hard time testing everything it contains and I am a bit scared to introduce all these changes at once. The branch at the moment crashes if there are previous evaluations but no terms loaded in the database.

I could start doing the splitting and then we could review and test one feature at the time. What do you think?

2021-06-30 13:57 UTC, mhkc commented
I dont really se how we can go smaller since one builds on top of another.

I guess we could add the changes to the institute config page later but that is a minor thing.

Also we kind of need this one at latest in late August due to the accreditation

2021-06-30 14:55 UTC, northwestwitch commented
> @northwestwitch I dont really se how we can go smaller since one builds on top of another. We need the core functionality of having the terms in the database. In order to make it usable we need both a set of default terms to be loaded during setup and the appropriate cli commands for working with the terms
> 
> I guess we could add the changes to the institute config page later but that is a minor thing.
> 
> Also we kind of need this one at latest in late August due to the accreditation

Have you checked my #2675? It's a basic version of this one that customizes also other types of terms. We could merge it easily but I need a reviewer

2021-12-15 09:12 UTC, closed without merging