Clearer warnings 4 gene search - 2 -
Clinical-Genomics/scout pull request #2671
Opened 2021-05-26 06:05 UTC by northwestwitch

Some changes I didn't manage to add to a previous PR since I've merged it by mistake!

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2021-05-27 07:58 UTC, northwestwitch commented
@mhkc do you have time for this easy review?

2021-05-28 06:08 UTC, dnil requested changes
How about these edits? Feel free to re-edit. And the request changes is only because you asked for it. I find it usually works out perfectly fine to Approve-with-some-caveats, but I can try this as well. 😉

2021-05-28 06:31 UTC, northwestwitch commented on scout/server/blueprints/variants/controllers.py
> +            "info": "Genes not included in gene panels versions used when loading variants of this case",
They're good. I'll apply!

2021-05-28 06:32 UTC, northwestwitch commented on scout/server/blueprints/variants/controllers.py
> +            "info": "Gene panels versions used for loading variants of this case contain outdated genes symbols",
I think users didn't understand what clinical list is so I'd avoid the term

2021-05-28 06:44 UTC, northwestwitch commented
> I find it usually works out perfectly fine to Approve-with-some-caveats, but I can try this as well.

To be perfectly honest with you the merging of the previous PR went like this: I was working on the sofa and while leaning in to reach a bag of chips, I inadvertently push the merge button with a part of my body that is not a finger ..

2021-05-28 06:46 UTC, dnil approved these changes

2021-05-28 06:48 UTC, merged