Show ACMG classification for pinned variants
Clinical-Genomics/scout pull request #2676
Opened 2021-05-27 11:46 UTC by mhkc

Show the ACMG classification for pinned variants

![image](https://user-images.githubusercontent.com/12696913/119820555-e26b2300-bef1-11eb-8bb4-f9baa2790272.png)

**Review:**
- [ ] code approved by
- [ ] tests executed by

2021-05-27 13:09 UTC, northwestwitch commented
RD case:

Master:

![image](https://user-images.githubusercontent.com/28093618/119831076-316a8580-befd-11eb-93cf-7c07223b8e1f.png)

This branch:

![image](https://user-images.githubusercontent.com/28093618/119831149-46471900-befd-11eb-8ebf-62c26f85a912.png)


Adding another classified pinned variant: 
![image](https://user-images.githubusercontent.com/28093618/119831324-75f62100-befd-11eb-849e-3f2ed40b96b3.png)

2021-05-27 13:11 UTC, northwestwitch requested changes
You forgot to pass the variant

2021-05-27 13:11 UTC, northwestwitch commented on scout/server/blueprints/cases/templates/cases/utils.html
> +                      {{ acmg_classification_badge }}
```suggestion
                      {{ acmg_classification_badge(variant) }}
```

2021-05-27 13:24 UTC, northwestwitch commented on CHANGELOG.md
> +- Show ACMG classification for pinned variants in case view
```suggestion
- Show manual ACMG classification for pinned variants in case view
```

2021-05-27 14:11 UTC, northwestwitch requested changes

2021-05-28 05:38 UTC, northwestwitch commented on scout/server/blueprints/variants/templates/variants/indicators.html
> +{% macro acmg_classification_badge(variant) %}
Yes: if you have the code in a separate macro, case page looks like this:

![image](https://user-images.githubusercontent.com/28093618/119935251-7cc97600-bf87-11eb-9061-8fc90424118b.png)

But variantS page doesn't show the badge:

![image](https://user-images.githubusercontent.com/28093618/119935336-a387ac80-bf87-11eb-91a1-6cea3df4542b.png)


But if you include the code of this macro in the macro above:

![image](https://user-images.githubusercontent.com/28093618/119935284-894dce80-bf87-11eb-9ddf-e6351ed02940.png)

2021-05-28 05:45 UTC, northwestwitch approved these changes

2021-05-28 05:45 UTC, northwestwitch commented on scout/server/blueprints/cases/templates/cases/utils.html
> +                      {{ acmg_classification_badge(variant) }}
👍🏻

2021-05-28 06:20 UTC, dnil commented
Sorry to barge in, but I'm still seeing double ACMG calls for the pinned ones? That cannot be intended, right? We usually stick with showing the classification, regardless if it was made using the tool or just manually entered - though there are some old issue there somewhere.

2021-05-28 06:30 UTC, northwestwitch commented
> Sorry to barge in, but I'm still seeing double ACMG calls for the pinned ones? That cannot be intended, right? We usually stick with showing the classification, regardless if it was made using the tool or just manually entered - though there are some old issue there somewhere.

Yeah I don't know. Perhaps he was asked to display in a badge how the classification was done?

2021-05-28 06:57 UTC, mhkc commented
I had some reports that ACMG classifications made with scout were missing in the pinned variants. They seem not to be included in the `clinical_assessments` and they are just present in `acmg_classification`

2021-05-28 07:31 UTC, northwestwitch commented
OK let's perhaps wait to merge this one. Let's make sure that the functionality doesn't work already and what and where can be improved

2021-06-03 08:11 UTC, northwestwitch commented
@mhkc to answer your question the other badge is shown when you click on the acmg classsification buttons or you use the tool by clicking on the button immediately under. So the code of this PR looks redundant.

![image](https://user-images.githubusercontent.com/28093618/120610812-d7fddb80-c453-11eb-9acb-f00e2ed427c9.png)

BUT!

I've checked what could be wrong with the missing ACMG for pinned variants and I've found out that pinned classified STRs don't actually have an ACMg badge on case page. Look for instance at this example: top variant is a SNV, bottom variant is a STR. Both with ACMG classification:

![image](https://user-images.githubusercontent.com/28093618/120609744-ca942180-c452-11eb-9dab-6b17ff72b9ce.png)

Could this be the original problem found by clinicians in Lund?

2021-06-03 08:31 UTC, dnil commented
Formally STRs don't have ACMG. They could and should have other variant tags. I guess pragmatically, someone may be using the ACMG classification for them anyway, treating it more as guidelines. https://gph.is/g/EJmDXnV

2021-06-03 08:34 UTC, northwestwitch commented
> Formally STRs don't have ACMG. They could and should have other variant tags. I guess pragmatically, someone may be using the ACMG classification for them anyway, treating it more as guidelines.
> ![image](https://user-images.githubusercontent.com/758570/120613894-f4e7de00-c456-11eb-908a-39acb63bb7e4.png)

I knew this comment was coming from the moment I wrote mine! 😆

2021-06-17 11:35 UTC, northwestwitch commented
I've realized that we actually have a bug (see also issue #2710) causing not only ACMG classification to be missing in pinned panel, but also dismissed status, manual rank, tier and mosaic status missing in causatives panel as well. 
I've written a PR (#2713) that should cover all this, so I'm closing this one.

2021-06-17 11:35 UTC, closed without merging