Update login page logos
Clinical-Genomics/scout pull request #2758
Opened 2021-07-13 13:08 UTC by mhkc

** DO NOT MERGE **

This is a draft PR.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2021-07-26 12:19 UTC, mikaell commented
Did you update the documentation?

2021-07-27 14:28 UTC, mhkc commented
Nope, forgot to do that.  Ill fix it tomorrow

2021-07-30 09:29 UTC, mikaell requested changes
Code Looks good and all tests pass -only needs to handle the case of badly configured image path (and maybe a pytest for that 🙂).

2021-07-30 09:29 UTC, mikaell commented on scout/server/blueprints/public/views.py
> +    badge_name = current_app.config.get("ACCREDITATION_BADGE")
Check if badge image exists (here or elsewhere) and give reasonable warning, and either add placeholder text or hide the image element html.

2021-07-30 13:11 UTC, mikaell approved these changes
Nice!

2021-07-30 13:11 UTC, mikaell commented on scout/server/blueprints/public/views.py
> +    if badge_name and not Path(public_bp.static_folder, badge_name).is_file():
👍

2021-08-02 08:07 UTC, merged