Fix/severity text #2808
Clinical-Genomics/scout pull request #2845
Opened 2021-09-02 11:20 UTC by mikaell

This PR fixes a bug: https://github.com/Clinical-Genomics/scout/issues/2808

This PR removes Span-tag for list items in Severity box, on a variant page, allowing for smoother rendering when base window is narrow.

**How to test**:
1. how to test it, possibly with real cases/data

Go to a cancer variant and make browser window narrow. Some lists of strings in the *Severity box* will render strangely. See picture.

![image](https://user-images.githubusercontent.com/1150065/131833786-3dc96a89-2b56-4a5c-8408-a8d8bfcec3e2.png)

2. Install patch, 

**Expected outcome**:
The functionality should be working. Try to narrow the browser page and the text should render smoothly and align within the box. However, way too narrow browser windows will always look strange.

![image](https://user-images.githubusercontent.com/1150065/131833482-6ff90dce-6805-4ca2-ab57-88b5ce9c10bd.png)

**Review:**
- [ ] code approved by 
- [ ] tests executed by

2021-09-02 12:29 UTC, mikaell commented
This needs more local testing before review. I will let you know when it is ready.

2021-09-03 07:04 UTC, northwestwitch requested changes
The fix to the severity panel works nicely! 👍🏻 

Are the other changes to the code (cosmic buttons) intended or they're inherited from tests on another branch?

2021-09-03 07:04 UTC, northwestwitch commented on scout/server/blueprints/variant/templates/variant/variant_details.html
> +          {% if variant.sift_predictions  %}
Works nicely! I won't add screenshots since they look like your example on the PR description!

2021-09-10 08:46 UTC, mikaell commented on scout/server/blueprints/variant/templates/variant/cancer-variant.html
> +            <a data-toggle="tooltip" title="{{cosmic_link.split('search?q=')[1]}}" class="btn btn-sm btn-info text-white" role="button" href="{{cosmic_link}}" target="_blank">COSMIC</a>
This was not intended. Will move to master's functionality.

2021-09-10 09:05 UTC, mikaell commented on scout/server/links.py
> +        cosmic_links.append(url_template.format(cosmic_id))
I do not remember…

2021-09-10 09:39 UTC, mikaell commented on scout/server/blueprints/variant/templates/variant/cancer-variant.html
> +            <a data-toggle="tooltip" title="{{cosmic_link.split('search?q=')[1]}}" class="btn btn-sm btn-info text-white" role="button" href="{{cosmic_link}}" target="_blank">COSMIC</a>
Should be reverted to master.

2021-09-10 09:39 UTC, mikaell commented on scout/server/blueprints/variant/templates/variant/cancer-variant.html
> +            <a class="btn btn-sm btn-info text-white" role="button" target="_blank" href="{{variant.snp_links[snp]}}">dbSNP ({{ snp }})</a>
Should be reverted to master.

2021-09-10 09:39 UTC, mikaell commented on scout/server/links.py
> +        cosmic_links.append(url_template.format(cosmic_id))
Should be reverted to master.

2021-09-10 10:56 UTC, mikaell commented
Cosmic links are as master and Severity section line breaks as intended.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1150065/132843282-be3499f5-8726-485a-ba4b-ff44e4787558.png">

2021-09-10 11:01 UTC, northwestwitch approved these changes
Looks good now!

2021-09-10 11:01 UTC, northwestwitch commented on scout/server/blueprints/variant/templates/variant/variant_details.html
> +          {% if variant.polyphen_predictions %}
Looks good!

2021-09-10 11:02 UTC, merged