Reassign MME cases to another user when a Scout user is removed
Clinical-Genomics/scout pull request #2985
Opened 2021-11-18 10:44 UTC by northwestwitch

Fix #2979

**How to test**:
1. In a terminal, start a MatchMaker exchange server with demo data:
```
git clone https://github.com/Clinical-Genomics/patientMatcher.git
cd patientMatcher

docker-compose up
```
2. In a local instance of Scout, demo config file (config.py), uncomment these lines: 
```
MME_ACCEPTS = "application/vnd.ga4gh.matchmaker.v1.0+json"
MME_URL = "http://localhost:9020"
MME_TOKEN = "DEMO"
```
3. Modify demo user and grant him permission to share cases to MatchMaker:
```
scout --demo update user -u clark.kent@mail.com -r mme_submitter
```
4. Launch the web app of Scout, pin a variant and share it to the MatchMaker.
Check in MongoDB compass, where a submission object dictionary should have been created for the demo case

5. Try to delete the demo user with the command, it should fail because it has one MME submission associated
```
scout --demo delete user -m clark.kent@mail.com
```

......

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2021-11-18 12:24 UTC, northwestwitch commented
1. If the case is not assigned to another user, then demo user Clark Kent can't be removed:
![image](https://user-images.githubusercontent.com/28093618/142413657-82efbc66-7dd0-4f55-a4d4-99b66935449b.png)

2. Assign the case to a user with email not present in Scout:
![image](https://user-images.githubusercontent.com/28093618/142413959-63642e98-7028-4029-a78a-f2e1c4de9d3a.png)

3. Create a new user that is not a MME submitter and use it for reassigning the case:
![image](https://user-images.githubusercontent.com/28093618/142414171-d16a7ee5-4bbd-4919-a7ca-8d5329c56cfa.png)

![image](https://user-images.githubusercontent.com/28093618/142414277-120c910a-3346-44a3-905c-6943a706a7e2.png)

4. Update new user with mme_submitter role:
![image](https://user-images.githubusercontent.com/28093618/142414405-cde7d473-7917-4783-ac18-dfb8ad4be2dc.png)

5. Try again to remove demo user Clark Kent:
![image](https://user-images.githubusercontent.com/28093618/142414595-e1882a96-f993-4b20-b3b6-ee9b051e2371.png)

User is removed from database:
![image](https://user-images.githubusercontent.com/28093618/142414667-3a9697f5-2c10-41c9-abc9-8bd15c623154.png)

Case submission is updated:
![image](https://user-images.githubusercontent.com/28093618/142414749-4c2f0954-9b3f-4389-9ecd-3638a038e8f8.png)

A new event is created when the MME contact is modified:
![image](https://user-images.githubusercontent.com/28093618/142414856-f3430d6b-a4bb-49b4-bd09-2eef1e86b5f6.png)

2021-11-18 14:42 UTC, northwestwitch commented
This is ready for review now!

2021-11-29 08:58 UTC, northwestwitch commented
I'm working on the PatientMatcher paper revision and I'm including this feature in the text. This means we should try to merge this PR as soon as possible..

2021-12-16 08:56 UTC, mikaell commented
I think it should be more explicit that the user will be deleted only if the matchmaker is reassigned.

```
(py3.8) Mikael@mikaellmbp:scout% scout delete user -m ml@mail.com
2021-12-16 09:55:05 mikaellmbp scout.commands.base[75670] INFO Running scout version 4.45
2021-12-16 09:55:05 mikaellmbp scout.commands.base[75670] DEBUG Debug logging enabled.
2021-12-16 09:55:05 mikaellmbp scout.adapter.client[75670] INFO Connected to MongoDB 4.0.3
2021-12-16 09:55:05 mikaellmbp scout.adapter.mongo.base[75670] DEBUG Database name: scout
2021-12-16 09:55:05 mikaellmbp scout.commands.delete.delete_command[75670] INFO Running scout delete user
2021-12-16 09:55:05 mikaellmbp scout.adapter.mongo.user[75670] INFO Fetching user ml@mail.com
2021-12-16 09:55:05 mikaellmbp scout.adapter.mongo.case[75670] INFO Fetching case internal_id
MatchMaker Exchange submissions (n. cases=1) are associated to this user. Reassign patients to another user? [y/N]: N
Aborted!
```

2021-12-16 09:00 UTC, northwestwitch commented on scout/commands/delete/delete_command.py
> +            f"MatchMaker Exchange submissions (n. cases={len(mme_submitted_cases)}) are associated to this user. Reassign patients to another user?",
Something like this @mikaell ?

2021-12-16 09:07 UTC, mikaell commented on scout/commands/delete/delete_command.py
> +            f"MatchMaker Exchange submissions (n. cases={len(mme_submitted_cases)}) are associated to this user. Reassign patients to another user?",
Perfect!

2021-12-16 09:17 UTC, mikaell requested changes
Looks good! 

But I found a typo. I should be fixed as it has been spotted 🙂

2021-12-16 09:17 UTC, mikaell commented on scout/adapter/mongo/matchmaker.py
> +            # Check that the cases patient's submission are stll actual
Typo: still

2021-12-16 09:19 UTC, mikaell approved these changes

2021-12-16 13:23 UTC, northwestwitch commented
Thank you, merging now!

2021-12-16 13:44 UTC, merged