Export verified variants from all institutes when user is admin
Clinical-Genomics/scout pull request #3117
Opened 2022-01-26 15:52 UTC by northwestwitch

This PR adds a functionality or fixes a bug.
OR
This PR marks a new Scout release. We apply semantic versioning. This is a major/minor/patch release for reasons.

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. `ssh your.email@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2022-01-26 15:59 UTC, northwestwitch commented
Downloaded files using master branch:

![image](https://user-images.githubusercontent.com/28093618/151198917-daf5de87-5c18-4fc1-8afb-eca2f8d8a5d3.png)

Downloaded files using THIS branch:

![image](https://user-images.githubusercontent.com/28093618/151198599-f97743dc-11e3-489c-81fc-d94013d8d58c.png)

2022-01-27 12:08 UTC, dnil requested changes
Suggest reverting to using user_obj to fetch institutes for non privileged users!

2022-01-27 12:08 UTC, dnil commented on scout/server/blueprints/variants/views.py
> +from flask import Blueprint, flash, redirect, request, send_file, url_for
🧹

2022-01-27 12:08 UTC, dnil commented on scout/server/blueprints/variants/views.py
> +    user_institutes = (
Simple and effective! 🥇

2022-01-27 12:08 UTC, dnil commented on scout/server/blueprints/variants/views.py
> +        else current_user.get("institutes")
Oh, but that won't work for non admins, right? LoginUser is a UserMixin, not a Scout user obj/dict?
```
2022-01-27 13:04:58 k1315C02VR0WRHTDH scout.server.app[88833] ERROR Exception on /verified [GET]
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dannil/sandbox/scout/scout/server/blueprints/variants/views.py", line 540, in download_verified
    else current_user.get("institutes")
  File "/usr/local/miniconda3/envs/scout39/lib/python3.9/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'LoginUser' object has no attribute 'get'
```

2022-01-27 12:08 UTC, dnil commented on scout/server/blueprints/variants/views.py
> +        else current_user.get("institutes")
```suggestion
        else user_obj.get("institutes")
```

2022-01-27 12:09 UTC, dnil commented on scout/server/blueprints/variants/views.py
> +    user_institutes = (
```suggestion
    user_obj = store.user(current_user.email)

    user_institutes = (
```

2022-01-27 13:06 UTC, northwestwitch commented
> Suggest reverting to using user_obj to fetch institutes for non privileged users!

Right, otherwise it crashes, good suggestion! :)

2022-01-27 13:34 UTC, merged