Colorize genetic models on variantS page
Clinical-Genomics/scout pull request #3665
Opened 2022-11-11 13:59 UTC by northwestwitch

Second partial fix #3631. **TO BE REVIEWED PREFERABLY AFTER #3664**, because contains code from it.

Changes RD variantS table from this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28093618/201355400-2e560ec0-6ba2-4537-a230-47c1d6aac9a6.png">

To this:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28093618/201355333-ff197b83-ee10-44bb-80ad-f5ddd62b2e30.png">

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, log out from `cg-vm1` and log in again in the `hasta` server, repeat the `hasta` and `paxa` procedure, which will release the allocated resource (scout-stage) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by

2022-11-15 09:12 UTC, dnil requested changes

2022-11-15 09:12 UTC, dnil commented on scout/constants/variant_tags.py
> +    "AR_hom": INHERITANCE_PALETTE["AR"],
Here I think we will want a graded intensity. AR should be more visible than AR_comp (which anyway has a Compund button connected, and will be nice with a thematic color), AD_dn more intense than AD etc.

2022-11-15 09:12 UTC, dnil commented on scout/constants/variant_tags.py
> +GENETIC_MODELS_PALETTE = {
👍 Good with the same base colors!

2022-11-16 10:01 UTC, northwestwitch commented
I'm working on the graded intensity and I've found a solution using opacity. Works nicely on light mode:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/28093618/202149974-198d8a0f-5ba0-438a-bda0-d9eee467e2b8.png">


But it doesn't render OK on dark mode: 😢 

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/28093618/202150106-0c85ee9b-a064-455b-a90b-1e2dd3a18e92.png">

2022-11-16 14:51 UTC, northwestwitch commented
Ok, I've modified the genetic models (variantS oage) like this:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/28093618/202213133-1e76a4bc-63bb-4aed-b5af-df9df991a7e9.png">

And the inheritance models (variant page) like this:

<img width="143" alt="image" src="https://user-images.githubusercontent.com/28093618/202212177-c77d4224-e49c-406c-8b5b-0ffecdf8cebc.png">

2022-11-21 16:49 UTC, dnil approved these changes
Looks good! If you want, I could have a look at your opacity fix - maybe I could coerce the dark mode - but otherwise it is ok like this, isn't it?

2022-11-22 07:33 UTC, northwestwitch commented
> Looks good! If you want, I could have a look at your opacity fix - maybe I could coerce the dark mode - but otherwise it is ok like this, isn't it?

The opacity fix looks really nice on the light theme. I have tried to force the badges to stay in light mode also if the system is in dark mode with this css style: `color-scheme: only light;` but didn't work. If you have time yes, give it a try (on another branch perhaps?) You can pull one of the intermediate commits of this branch in the new branch and test. Thanks!

2022-11-22 08:23 UTC, dnil commented
> > Looks good! If you want, I could have a look at your opacity fix - maybe I could coerce the dark mode - but otherwise it is ok like this, isn't it?
> 
> The opacity fix looks really nice on the light theme. I have tried to force the badges to stay in light mode also if the system is in dark mode with this css style: `color-scheme: only light;` but didn't work. If you have time yes, give it a try (on another branch perhaps?) You can pull one of the intermediate commits of this branch in the new branch and test. Thanks!

Hm, you may only have done this on your local? Couldn't find the commit? Anyway, its nice enough this way so agreed, new branch and at QOL priority. Meeting ahead...

2022-11-22 08:47 UTC, northwestwitch commented
> Hm, you may only have done this on your local?

Perhaps! A disadvantage of **opacity** is that the default style applied to badge color but also badge text. 

I remember using the --bs-bg-opacity style: https://getbootstrap.com/docs/5.2/utilities/background/#opacity

2022-11-22 10:56 UTC, dnil commented
> > Hm, you may only have done this on your local?
> 
> Perhaps! A disadvantage of **opacity** is that the default style is applied to badge color but also badge text. Example: https://getbootstrap.com/docs/5.1/utilities/opacity/
> 
> I remember using the `bg-opacity-x` style: https://getbootstrap.com/docs/5.2/utilities/background/#opacity

Looks super sweet! Let's see, aren't we/darkmode still on 5.0? Perhaps we should update..

2022-11-22 11:05 UTC, dnil commented
> > Perhaps! A disadvantage of **opacity** is that the default style is applied to badge color but also badge text. Example: https://getbootstrap.com/docs/5.1/utilities/opacity/
> > I remember using the `bg-opacity-x` style: https://getbootstrap.com/docs/5.2/utilities/background/#opacity
> 
> Looks super sweet! Let's see, aren't we/darkmode still on 5.0? Perhaps we should update..

Yeah, well, bootstrap dark stopped main at 5.1.3, since the 5.2-beta color changes were rather big. There is now also a less intrusive dark mode version with only the deltas, not the whole base css:  bootstrap-dark-plugin, but I think its also just at 5.1.3. 

It seems right now they will not fix the core issue with 5.2 in the 5.x, delaying it for v6 https://github.com/twbs/bootstrap/issues/36458. Hmm, maybe absolute colors is not so bad... 😆

2022-11-22 11:08 UTC, dnil commented
> It seems right now they will not fix the core issue with 5.2 in the 5.x, delaying it for v6 [twbs/bootstrap#36458](https://github.com/twbs/bootstrap/issues/36458). Hmm, maybe absolute colors is not so bad... 😆

Ah, actually he does have a dev branch for 5.2: https://github.com/vinorodrigues/bootstrap-dark-5/tree/dev/v1.2.0
So we could do that, but...

2022-11-23 09:47 UTC, merged