Download orpha
Clinical-Genomics/scout pull request #4241
Opened 2023-11-28 11:49 UTC by TereseBo

This PR adds a functionality for downloading the xml of gene-disease relations (en_product6.xml) from Orphadata (https://www.orphadata.com/data/xml/en_product6.xml) and adds a command for separate download and also runs  on the download everything command.

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2023-12-05 11:25 UTC, northwestwitch requested changes
Nice! I've tested it locally and it works as expected! 🥇 

I have a few suggestions for improvement and readability of the code, see comments in the code!

And as discussed in the chat, would be easier to have isort and black integrated in the editor, so you avoid having errors in the linting checks also in the future

2023-12-05 11:25 UTC, northwestwitch commented on scout/utils/scout_requests.py
> +def fetch_orpha_files(product4=False, product6=False):
```suggestion
def fetch_orpha_files(orpha_hpo:bool=False, orpha_genes:bool=False)-> Dict[str,list]:
```

2023-12-05 11:25 UTC, northwestwitch commented on scout/utils/scout_requests.py
> +    Returns:
This can be removed if you have type hints

2023-12-05 11:25 UTC, northwestwitch commented on scout/utils/scout_requests.py
> +    orphadata_en_product4_url = "https://www.orphadata.com/data/xml/en_product4.xml"
Rename this variable to something that makes sense to us and move it to scout.constants.phenotypes, so you can import it here and also in the test. Better to specify it in one place only so if it changes you fix it there and you don't have to go and chase it down to all the places where it is written.

2023-12-05 11:25 UTC, northwestwitch commented on scout/utils/scout_requests.py
> +    orphadata_en_product6_url = "https://www.orphadata.com/data/xml/en_product6.xml"
Same here

2023-12-05 11:25 UTC, northwestwitch commented on scout/utils/scout_requests.py
> +    if product4 is True:
I don't think we would have any situations where we want to only include only ORPHA terms from one of the files, no?

2023-12-05 11:25 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +    url = "https://www.orphadata.com/data/xml/en_product4.xml"
Import this URL from scout.constants.phenotypes instead

2023-12-05 11:25 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +    url = "https://www.orphadata.com/data/xml/en_product6.xml"
Same here, import from constants

2023-12-05 11:25 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +        content = orphadata_en_product4_file.read()
Add type hint to content

2023-12-05 11:25 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +        the_dir = pathlib.Path(dir_name)
Type hint

2023-12-05 11:25 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +        downloaded_files = os.listdir(dir_name)
Type hint

2023-12-05 11:25 UTC, northwestwitch commented on scout/commands/download/orpha.py
> +        file_path = out_dir / file_name
type hint

2023-12-05 11:25 UTC, northwestwitch commented on scout/commands/download/orpha.py
> +    out_dir = pathlib.Path(out_dir)
type hint

2023-12-05 14:34 UTC, TereseBo commented on scout/commands/download/orpha.py
> +def print_orpha(out_dir):
I apparently was a  pathlib.Path and not string, have updated with typing

2023-12-06 13:21 UTC, northwestwitch approved these changes
Looks great! I have very few comments, but it's working and looks good! 💯

2023-12-06 13:21 UTC, northwestwitch commented on scout/commands/download/orpha.py
> +    """Downloads orphadata product4 (Orphacodes mapped to HPO)
🥇

2023-12-06 13:21 UTC, northwestwitch commented on scout/commands/download/orpha.py
> +    orpha_files: Dict = fetch_orpha_files()
```suggestion
    orpha_files: Dict[str,str] = fetch_orpha_files()
```

2023-12-06 13:21 UTC, northwestwitch commented on scout/commands/download/omim.py
> +def print_omim(out_dir: Path, api_key: str) -> None:
I think it might be a PosixPath instead of a Path here?

2023-12-06 13:21 UTC, northwestwitch commented on scout/constants/phenotype.py
> +ORPHA_URLS = {
💯

2023-12-06 13:21 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +def test_download_orpha_cmd(empty_mock_app: app.Flask) -> None:
```suggestion
def test_download_orpha_cmd(empty_mock_app: app.Flask):
```

2023-12-06 13:21 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +def test_download_orpha_cmd(empty_mock_app: app.Flask) -> None:
I think it's OK to omit return types in tests, since they always return None

2023-12-06 13:21 UTC, northwestwitch commented on tests/commands/download/test_download_orpha_cmd.py
> +        assert "orphadata_en_product4.xml" in downloaded_files
👍🏻

2023-12-06 14:38 UTC, merged