Better ClinVar tooltips and added exclude clinsig status for SNVs filter
Clinical-Genomics/scout pull request #4993
Opened 2024-11-04 09:23 UTC by northwestwitch

This PR adds a functionality or fixes a bug.
- Fixes partially #4992 

### New checkbox

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/71ea6ab2-19bb-42fd-a9ec-3c00fc9bbf64">

### Better tooltip
<img width="440" alt="image" src="https://github.com/user-attachments/assets/d3fde21e-0af6-4146-bafa-fd53f058123b">

### New tooltip
<img width="572" alt="image" src="https://github.com/user-attachments/assets/4022423e-e973-4304-997e-4290ac75caf7">

### Note that this PR is only covering SNVs filters, I plan to add the exclude filter to the other categories in another PR (I think it's going to be easier to review this way)

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by DN
- [x] tests executed by DN, CR

2024-11-05 08:20 UTC, dnil requested changes
Super with the tooltip!

Looks nice, but I have a few issues with the functionality?
First, the exclude now seems exclusive, e.g. removing variants without clinvar hits. That is not intended. One would like to whittle down the list of variants, say avoiding seeing the ones that are known Benign or Likely benign, but seeing the rest.

Exclusion filtering on my local still seems bugged?
![Screenshot 2024-11-05 at 08 50 16](https://github.com/user-attachments/assets/1df92ca9-353d-4f4a-bc40-bcce666a9ecc)
I'll give it the benefit of the doubt if it works on stage (I have been messing with setup quite a bit) but I think we are not quite there yet?

I also still haven't quite wrapped my head around what would be supposed to happen if you check exclude and high significance, but giving the high significance priority is needed for clincal filter, so all good.

2024-11-05 08:20 UTC, dnil commented on CHANGELOG.md
> +- Improved tooltips fpr ClinVar filter in SNVs filter form
```suggestion
- Improved tooltips for ClinVar filter in SNVs filter form
```

2024-11-05 08:20 UTC, dnil commented on scout/adapter/mongo/query.py
> +            clnsig_query = {"clnsig": {"$elemMatch": {"$or": elem_match_value}}}
Keep missing value!

2024-11-05 09:00 UTC, northwestwitch commented on scout/adapter/mongo/query.py
> +            clnsig_query = {"clnsig": {"$elemMatch": {"$or": elem_match_value}}}
Good point, I'll fix, thanks!

2024-11-05 11:01 UTC, northwestwitch commented on scout/adapter/mongo/query.py
> +    def clinsig_query(self, query: dict) -> dict:
This function is only refactored, but it returns the same dict as before

2024-11-11 11:59 UTC, northwestwitch commented
I'll wait for this one until we have #5006 in place, because they are touching the same code

2025-02-18 14:43 UTC, northwestwitch commented
This one is ready for review now!

2025-02-24 09:21 UTC, dnil commented
By the way, this should close #2654 as well, right!

2025-02-24 09:25 UTC, northwestwitch commented
> By the way, this should close #2654 as well, right!

Right! 😀

2025-02-24 10:29 UTC, northwestwitch commented on scout/adapter/mongo/query.py
> +                    "$nor": [
Good suggestion, I was also thinking to fix it this way

2025-02-24 10:43 UTC, merged