Fix filters parse and display
Clinical-Genomics/scout pull request #5061
Opened 2024-11-22 09:49 UTC by dnil

This PR adds a functionality or fixes a bug.

- Fix #5060 

Bit of a difference already without touching parsing:
![Screenshot 2024-11-22 at 10 44 30](https://github.com/user-attachments/assets/6a610836-0a8e-416b-b25e-0320d8aec2f0)

<details>
<summary>Testing on cg-vm1 server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. Make sure the PR is pushed and available on [Docker Hub](https://hub.docker.com/repository/docker/clinicalgenomics/scout-server-stage)
1. Fist book your testing time using the Pax software available at [https://pax.scilifelab.se/](https://pax.scilifelab.se). The resource you are going to call dibs on is `scout-stage` and the server is `cg-vm1`.
1. `ssh <USER.NAME>@cg-vm1.scilifelab.se`
1. `sudo -iu hiseq.clinical`
1. `ssh localhost`
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `podman ps`
1. Stop the service with current deployed branch: `systemctl --user stop scout.target`
1. Start the scout service with the branch to test: `systemctl --user start scout@<this_branch>`
1. Make sure the branch is deployed: `systemctl --user status scout.target`
1. After testing is done, repeat procedure at [https://pax.scilifelab.se/](https://pax.scilifelab.se), which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

<details>
<summary>Testing on hasta server (Clinical Genomics Stockholm)</summary>

**Prepare for testing**
1. `ssh <USER.NAME>@hasta.scilifelab.se`
1. Book your testing time using the Pax software. `us; paxa -u <user> -s hasta -r scout-stage`. You can also use the WSGI Pax app available at [https://pax.scilifelab.se/](https://pax.scilifelab.se).
1. (optional) Find out which scout branch is currently deployed on cg-vm1: `conda activate S_scout; pip freeze | grep scout-browser`
1. Deploy the branch to test: `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_scout -t scout -b <this_branch>`
1. Make sure the branch is deployed: `us; scout --version`
1. After testing is done, repeat the `paxa` procedure, which will release the allocated resource (`scout-stage`) to be used for testing by other users.
</details>

**How to test**:
1. how to test it, possibly with real cases/data

**Expected outcome**:
The functionality should be working
Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by

2024-11-22 09:57 UTC, dnil commented
Ok, with that out of the world, I would say we are not formally bugged at least not based on the demo case situation.
![Screenshot 2024-11-22 at 10 53 13](https://github.com/user-attachments/assets/21a475ca-90cc-4881-83c3-3fa21fc0e4ed)
Since the `set` tag is used without a "filteredIn", it is hard to fault the parsing here. This looks like more like a merging/pipeline issue.

But we could perhaps do slightly better here: since there is only one caller given, we could assign the FILTERS status to the call I think!

2024-11-22 12:48 UTC, dnil commented on scout/parse/variant/callers.py
>              filter_status = "Filtered - {}".format(filter_status.replace(";", " - "))
Note that `filter_status` could never take any other value than "Pass" here really, so it was either "Pass" or "Filtered - Pass" I guess?!

2024-11-22 13:36 UTC, dnil commented on scout/parse/variant/callers.py
> +    If the FILTER status is not PASS (e.g. None - cyvcf2 FILTER is None if VCF file column FILTER is "PASS"),
I dunno, this function is getting long. If I didn't have the thought about a new parsing module nudging I might split/refactor it. Say if you feel it is way long already.

2024-11-22 13:38 UTC, dnil commented on scout/parse/variant/callers.py
> +        filter_status_default = "Filtered - {}".format(variant.FILTER.replace(";", " - "))
This is one of the crucial changes. As noted below at its origin, the previous version would never add the actual FILTER tag on parsing. Python lazy initiation error. That would just have been a compile error in another language.

2024-11-22 13:39 UTC, dnil commented on scout/parse/variant/callers.py
> +        if len(infos) > 1:
As per the doctoring: add filter status if we are looking at a single caller, else just set as before.

2024-11-22 13:43 UTC, dnil commented on scout/server/blueprints/variants/templates/variants/utils.html
> +      <span class="badge {% if caller == 'Pass' %}bg-success{% elif 'Filtered' in caller %}bg-secondary{% else %}bg-black{% endif %}" data-bs-toggle="tooltip" data-bs-html="true" title="{{caller}}">
Show if substring matches, as in "Filtered - MinSomaticScore".

2024-11-25 07:03 UTC, northwestwitch commented
Just to understand, when there is filter passed but not a specific caller, then originally the filter was not "Passed" but "filtered"?

2024-11-25 08:02 UTC, northwestwitch requested changes
This seems to capture more filtered events, as oppsite to what happens on main branch, which is nice! 
Would be nice to: 
- Split the parsing function into different smaller functions, as you also suggested.
- Fix the filter label displayed on variantS page, because it's too long for that cell.

I'm still trying to understand why we still have the green PASS label with or without callers for some cancer variants. I guess I have to look inside the VCF

2024-11-25 15:36 UTC, dnil commented
> I'm still trying to understand why we still have the green PASS label with or without callers for some cancer variants. I guess I have to look inside the VCF

Yes, there are some lines there that appear odd to my understanding, much like if it was an amalgamation of different pipeline runs or call sets. I guess the demo is a) old and b) perhaps not entirely representative of one pipeline version, but has some edited lines etc.

2024-11-25 16:14 UTC, dnil commented
> Just to understand, when there is filter passed but not a specific caller, then originally the filter was not "Passed" but "filtered"?

Hm, no, I thought it would have been Pass and None on all callers for the category?

2024-11-26 06:56 UTC, northwestwitch approved these changes
Nice with the refactoring and new tests! 💯

2024-11-26 06:56 UTC, northwestwitch commented on CHANGELOG.md
> +
```suggestion
```

2024-11-26 06:56 UTC, northwestwitch commented on scout/parse/variant/callers.py
> +def parse_callers(variant: cyvcf2.Variant, category: str = "snv") -> dict:
🏅

2024-11-26 06:56 UTC, northwestwitch commented on scout/parse/variant/callers.py
> +        filter_status_default = "Pass"
This could also be a constant, outside this function.

2024-11-26 06:56 UTC, northwestwitch commented on tests/parse/test_parse_callers.py
> +def test_parse_callers_complex_filter(cyvcf2_variant):
👍🏻

2024-11-26 06:56 UTC, northwestwitch commented on tests/parse/test_parse_callers.py
> +def test_parse_callers_filtered_svdb_info(cyvcf2_variant):
👍🏻

2024-11-26 08:40 UTC, merged